spring:
  application:
    name: mailing
  mail:
    host: smtp.mailtrap.io
    port: 2525
    username: 59f01c77de1380
    password: 470725594c38f9
    protocol: smtp
    test-connection: false
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: false
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true

server:
  port: 0