spring:
  application:
    name: product
  datasource:
    driver-class-name: "com.mysql.cj.jdbc.Driver"
    url : jdbc:mysql://localhost:3306/product-service?createDatabaseIfNotExist=true
    username: root
    password: root

eureka:
    client:
        service-url:
            defaultZone: http://localhost:8761/eureka/
        fetch-registry: true
        register-with-eureka: true
server:
  port: 0